name: DeployToGitHubPages
env:
  PUBLISH_DIR: bin/Release/net7.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install WASM build tools
      run: dotnet workload install wasm-tools

    - name: Publish app
      run: dotnet publish -c Release

    - name: Download gpt-2 model
      run: curl -L --output ${{ env.PUBLISH_DIR }}/model/ggml-model.bin https://ggml.ggerganov.com/ggml-model-gpt-2-117M.bin

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /MLNetOnGithub/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
